### ISSUE TITLE
Telos Missing

### ISSUE THREAD

**Issue by GabrielGrimberg** [Majiick/MicroSim#3]
Good day Zan! I was just wondering if you're going to include the character we discussed about in this game? Remember, Telos? He plays an essential role in this simulator and therefore I think you should add him.

Regards,

Gabriel.

**Comment by Majiick** [comment]
RRRRRRRRRRRRRREEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 
![15996188_1278369282239506_867074177_n](https://cloud.githubusercontent.com/assets/14361865/22444470/fc2e9f80-e73a-11e6-8ac8-8b29ab46d84d.png)

**Comment by GabrielGrimberg** [comment]
Hello again Zan, this is not the character we were talking about, please see below for a true image of Telos.

Regards,

Gabriel.

![tess_pet](https://cloud.githubusercontent.com/assets/16061021/22444503/2918683c-e73b-11e6-99bf-dd4d36a7d57f.png)

**Comment by yungrazr** [comment]
Hello, may I intervene?
I suggest you add this character, The Great Olm, as it would be a much better fit for your "game".
Picture attached below))))
![image](https://cloud.githubusercontent.com/assets/23048761/22468848/cdb337e2-e7c1-11e6-957c-3fd39fc268e1.png)

**Comment by GabrielGrimberg** [comment]
Dear @yungrazr 

The character you have suggested is indeed a powerful creature that @Majiick should consider adding, although there is a new version called: Queen Black Dragon. I will include the image below. However before adding this boss, I extremely urge you to add Telos. In case you didn't know or have forgotten, Telos is a world guardian and it is essential to consider him in your simulator.

Regards,

Gabriel.

![j8uuogm](https://cloud.githubusercontent.com/assets/16061021/22469199/13750de0-e7c3-11e6-85cf-333e1f3fd2ce.jpg)
